###########################################
# Libs for "Fast" Language !              #
###########################################
# Coding By José Alexsandro               #
# Github: https://github.com/jsalexsandro #
###########################################


print_fast = [["<iostream>"],r"""/*
 * Write in Terminal
*/
template <class printT>
std::string print(printT values){
std::cout << values << std::endl;
return "null";
};
"""]

input_fast = [["<iostream>"],r"""/*
 * input
 * get input of the user
*/
template <typename inputT>
std::string input(inputT value = ""){
std::string s;
std::cout<<value;
std::getline(std::cin, s);
return s;
}
"""] 

types_fast = [["<iostream>","<typeinfo>","<stdlib.h>"],r"""/*
 * The Types
 * Type Converters and Type Identifiers
 * Code snippet generated by the language
 * Code in C++
*/


/* 
 * sendExcptions
 * Will put an error in the terminal
*/
template <class any>
any sendException (char * message,any &memorie,any value){
std::cout << "\nErro in Executable - " << 
message
<< "\nMemory address: " << &memorie 
<< "\nValue: " << value << std::endl;
exit(0);
return "null";
};

/*
 * type
 * take the kind of something
*/
template <typename any>
std::string type(any value){
std::string __type_return;
if (*(typeid(value).name()) == 'i' || *(typeid(value).name()) == 'l' || *(typeid(value).name()) == 'x'){
    __type_return = "int";
} else if (*(typeid(value).name()) == 'c'){
    __type_return = "char";        
} else if (*(typeid(value).name()) == 'P'){
    __type_return = "pointer";
} else if (*(typeid(value).name()) == 'b'){
    __type_return = "bool";
} else if (*(typeid(value).name()) == 'f' || *(typeid(value).name()) == 'd' || *(typeid(value).name()) == 'e'){
    __type_return = "float";
} else {
    // std::cout << typeid(value).name() << std::endl;
    __type_return = "string";
}
return __type_return;
}

/*
 * stringToInt
 * convert string to int
*/
long stringToInt(std::string _value){
int _start = 0;
int _end = _value.size();
std::string o_value;
while (_start != _end)
{
if (_value[_start] != ' '){
o_value += _value[_start];
}
_start +=1;
}
bool convert = false;
std::string value = o_value;
int start = 0;
int end = value.size();
if (end == 0){
sendException("It is only possible to convert valid strings to int",_value,_value);
}
while (start != end){
if (
value[start] == '0' ||
value[start] == '1' ||
value[start] == '2' ||
value[start] == '3' ||
value[start] == '4' ||
value[start] == '5' ||
value[start] == '6' ||
value[start] == '7' ||
value[start] == '8' ||
value[start] == '9'
){
convert = true;
} else {
char a = value[start+1];
if (
a == '0' ||
a == '1' ||
a == '2' ||
a == '3' ||
a == '4' ||
a == '5' ||
a == '6' ||
a == '7' ||
a == '8' ||
a == '9'
){

} else {
sendException("It is only possible to convert valid strings to int",_value,_value);
}
}
start ++;
}
if (convert == true){

long v = std::stoll(value,nullptr,10);
return v;
}  else {
sendException("It is only possible to convert valid strings to int",_value,_value);
}

}
"""
]

system_fast = [[],"""int system(std::string values){
int c = std::system(values.c_str());
}
"""
]