/*
 * C:\Users\Alexsandro\Desktop\FastLanguage\test\classErrorTest.fast
 * Code Generated by Fast lang
 * Version language: (0.0.1)
 * Tuesday 2021-08-17 18:07:54.886048
*/

#include <locale.h>
#include <iostream>

char ** argv;

/*
 * Write in Terminal
*/
template <class printT>
std::string print(printT values){
std::cout << values << std::endl;
return "null";
};

class classErrorTest{
public: classErrorTest(){
print(std::string("Test"));
this->App();
};
public: long App(){
print(std::string("Isso é Apenas um Teste"));
};
};


int main(int _argc,char * _argv[]){
setlocale(LC_ALL,"");
argv = _argv;
classErrorTest();
return 0;
};