/*
 * C:\Users\Alexsandro\Desktop\FastLanguage\test\inputEx.fast
 * Code Generated by Fast lang
 * Version language: (0.0.1)
 * Tuesday 2021-08-17 18:12:39.726521
*/

#include <iostream>
#include <locale.h>

char ** argv;

/*
 * input
 * get input of the user
*/
template <typename inputT>
std::string input(inputT value = ""){
std::string s;
std::cout<<value;
std::getline(std::cin, s);
return s;
}

/*
 * Write in Terminal
*/
template <class printT>
std::string print(printT values){
std::cout << values << std::endl;
return "null";
};

class inputEx{
public: inputEx(){
std::string value=input(std::string("? "));
print(value);
};
};


int main(int _argc,char * _argv[]){
setlocale(LC_ALL,"");
argv = _argv;
inputEx();
return 0;
};