/*
 * C:\Users\Alexsandro\Desktop\FastLanguage\test\nameError.fast
 * Code Generated by Fast lang
 * Version language: (0.0.1)
 * Tuesday 2021-08-17 23:45:41.451471
*/

#include <locale.h>
#include <iostream>

char ** argv;

/*
 * Write in Terminal
*/
template <class printT>
std::string print(printT values){
std::cout << values << std::endl;
return "null";
};

class nameError{
public: nameError(){
long value=0;
print(value);
};
};


int main(int _argc,char * _argv[]){
setlocale(LC_ALL,"");
argv = _argv;
nameError();
return 0;
};