/*
 * test.fast
 * Code Generated by Fast lang
 * Version language: (0.0.1)
 * Wednesday 2021-08-18 17:19:38.222723
*/

#include <locale.h>
#include <iostream>

char ** argv;

long soma(long c=0,long d=0){
return c-d;
};
long test(){
soma();
}

int main(int _argc,char * _argv[]){
setlocale(LC_ALL,"");
argv = _argv;
test();
return 0;
};