/*
 * C:\Users\Alexsandro\Desktop\FastLanguage\test\test.fast
 * Code Generated by Fast lang
 * Version language: (0.0.1)
 * Thursday 2021-08-19 21:36:25.263759
*/

#include <iostream>
#include <locale.h>

char ** argv;

long p(){
long s=10;
};
long test(){
long a=10;
p();
}

int main(int _argc,char * _argv[]){
setlocale(LC_ALL,"");
argv = _argv;
test();
return 0;
};