/*
 * test\test.fast
 * Code Generated by Fast lang
 * Version language: (0.0.1)
 * Thursday 2021-08-19 14:45:56.016497
*/

#include <locale.h>
#include <iostream>

char ** argv;

/*
 * Write in Terminal
*/
template <class printT>
std::string print(printT values){
std::cout << values << std::endl;
return "null";
};

long test(){
print(std::string("Olá, Mundo!"));
}

int main(int _argc,char * _argv[]){
setlocale(LC_ALL,"");
argv = _argv;
test();
return 0;
};